export const OMASUM_LEVELS = ['O0', 'O1', 'O2', 'O3', 'O4', 'O5'];
export const EVIDENCE_LEVELS = ['E0', 'E1', 'E2', 'E3', 'E4', 'E5'];
export const DEVELOPMENT_DISTANCES = ['D1', 'D2', 'D3', 'D4', 'D5'];

export const COMPANY_STATUSES = [
  '未联系',
  '已联系',
  '要视频',
  '待本地核实',
  '待拜访',
  '试加工',
  '试柜',
  '复购',
  '观察',
  '淘汰',
];

export const LOCAL_TASK_STATUSES = ['待处理', '进行中', '已完成', '暂停', '取消'];

export const COMPANY_HEADERS = [
  'source_id',
  'raw_company_name',
  'normalized_company_name',
  'country',
  'city',
  'company_type',
  'source_type',
  'url_or_file',
  'official_registration',
  'keywords_found',
  'excluded_keywords_found',
  'omasum_level',
  'evidence_level',
  'development_distance',
  'source_truth',
  'weekly_supply_potential',
  'undervaluation_signal',
  'processing_control',
  'route_feasibility',
  'communication_trust',
  'risk_flags',
  'score',
  'radar_score',
  'priority_grade',
  'status',
  'next_action',
  'notes',
  'updated_at',
];

export const SCAN_HISTORY_HEADERS = [
  'source_id',
  'url_or_file',
  'first_seen',
  'source_type',
  'raw_company_name',
  'normalized_company_name',
  'country',
  'status',
  'reason',
];

export const AUTO_LEAD_HEADERS = [
  'source_id',
  'raw_company_name',
  'country',
  'city',
  'company_type',
  'source_type',
  'url_or_file',
  'official_registration',
  'description',
  'notes',
];

export const COLLECTION_HISTORY_HEADERS = [
  'source_id',
  'collected_at',
  'source_type',
  'url',
  'status',
  'lead_count',
  'reason',
];

export const TRADE_ROUTE_HEADERS = [
  'route_id',
  'source',
  'collected_at',
  'reporter',
  'reporter_code',
  'partner',
  'partner_code',
  'hs_code',
  'period',
  'flow',
  'trade_value_usd',
  'net_weight_kg',
  'quantity',
  'route_strength',
  'source_url',
  'status',
  'notes',
];

export const TRADE_ROUTE_HISTORY_HEADERS = [
  'source_id',
  'collected_at',
  'status',
  'route_count',
  'reason',
];

export const BILL_OF_LADING_HEADERS = [
  'shipment_id',
  'source_file',
  'source_platform',
  'shipment_date',
  'shipper',
  'shipper_country',
  'consignee',
  'destination_country',
  'destination_port',
  'hs_code',
  'product_description',
  'quantity_kg',
  'container_count',
  'bill_of_lading_no',
  'source_url_or_file',
  'evidence_level',
  'development_distance',
  'notes',
];

export const FACTORY_CAPABILITY_HEADERS = [
  'capability_id',
  'country',
  'official_registration',
  'legal_name',
  'plant_name',
  'city',
  'region',
  'address',
  'activity_type',
  'animal_species',
  'operational_status',
  'export_markets',
  'product_scope',
  'byproduct_signal',
  'cold_chain_signal',
  'source_id',
  'source_url',
  'source_status',
  'confidence',
  'collected_at',
  'notes',
];

export const SLAUGHTER_CAPACITY_HEADERS = [
  'capacity_id',
  'country',
  'official_registration',
  'plant_name',
  'region',
  'period',
  'species',
  'category',
  'slaughter_head_count',
  'capacity_scope',
  'source_id',
  'source_url',
  'confidence',
  'collected_at',
  'notes',
];

export const EXPORT_APPROVAL_HEADERS = [
  'approval_id',
  'country',
  'official_registration',
  'plant_name',
  'destination_market',
  'product_category',
  'approval_status',
  'valid_from',
  'valid_to',
  'source_id',
  'source_url',
  'confidence',
  'collected_at',
  'notes',
];

export const RADAR_SCORE_HEADERS = [
  'radar_id',
  'source_id',
  'company_key',
  'normalized_company_name',
  'country',
  'official_score',
  'supply_score',
  'byproduct_score',
  'export_readiness_score',
  'market_whitespace_score',
  'contactability_score',
  'radar_score',
  'priority_grade',
  'invisible_supply_rationale',
  'recommended_verification',
  'capability_refs',
  'capacity_refs',
  'approval_refs',
  'scored_at',
];

export const RADAR_SOURCE_HEALTH_HEADERS = [
  'source_id',
  'country',
  'layer',
  'status',
  'retrieval',
  'row_count',
  'source_url',
  'reason',
  'collected_at',
];

export const LOCAL_TASK_HEADERS = [
  'task_id',
  'company_key',
  'normalized_company_name',
  'country',
  'city',
  'task_name',
  'task_type',
  'assignee',
  'must_ask',
  'must_capture',
  'due_date',
  'returned_result',
  'ai_processing_status',
  'conclusion',
  'status',
  'created_at',
];

export const EVIDENCE_HEADERS = [
  'evidence_id',
  'company_key',
  'normalized_company_name',
  'evidence_type',
  'date_received',
  'path_or_url',
  'summary',
  'is_current_batch',
  'omasum_level',
  'risk_points',
  'human_review',
  'evidence_level',
];

export const LLM_EVALUATION_HEADERS = [
  'evaluation_id',
  'evaluated_at',
  'engine',
  'source_id',
  'normalized_company_name',
  'base_score',
  'llm_score',
  'final_score',
  'omasum_level',
  'evidence_level',
  'development_distance',
  'route_feasibility',
  'status',
  'next_action',
  'risk_flags',
  'rationale',
  'citations',
  'report_path',
  'report_markdown',
  'guardrail_notes',
];

export const RISK_RULES = [
  {
    id: 'refuses_current_video',
    label: '拒绝提供当前视频',
    penalty: 15,
    terms: ['refuses current video', 'refuse current video', '拒绝提供当前视频', '不愿视频', 'no video'],
  },
  {
    id: 'unknown_material_source',
    label: '不说明原料来源',
    penalty: 15,
    terms: ['unknown material source', '不说明原料来源', 'source unclear', '来源不明'],
  },
  {
    id: 'prepayment_pressure',
    label: '只催预付款',
    penalty: 20,
    terms: ['prepayment pressure', 'only prepayment', '只催预付款', '先付款', '催预付款'],
  },
  {
    id: 'inconsistent_product',
    label: '产品描述前后不一致',
    penalty: 15,
    terms: ['inconsistent product', '产品描述前后不一致', '变成 mixed tripe', 'description changed'],
  },
  {
    id: 'registration_mismatch',
    label: '公司地址和注册信息对不上',
    penalty: 20,
    terms: ['registration mismatch', 'address mismatch', '注册信息对不上', '地址对不上'],
  },
  {
    id: 'low_price_no_evidence',
    label: '报价明显低但无证据',
    penalty: 20,
    terms: ['low price no evidence', '报价明显低但无证据', 'too cheap', '异常低'],
  },
  {
    id: 'refuses_visit',
    label: '不允许现场拜访',
    penalty: 15,
    terms: ['refuses visit', 'no visit', '不允许现场拜访', '不能拜访', '拒绝拜访'],
  },
  {
    id: 'agent_only',
    label: '只能通过代理，见不到源头',
    penalty: 10,
    terms: ['agent only', '只能通过代理', '见不到源头', 'cannot meet source'],
  },
  {
    id: 'mixed_tripe_risk',
    label: 'Omasum 与其他牛肚混装风险高',
    penalty: 15,
    terms: ['mixed tripe risk', 'mixed beef tripe', '混合牛肚', '混装', 'rumen', 'honeycomb tripe'],
  },
];

export const DEFAULT_PRECISE_TERMS = [
  'beef omasum',
  'bovine omasum',
  'book tripe',
  'leaf tripe',
  'bible tripe',
  'omaso bovino',
  'librillo bovino',
  'librillo',
  'omaso',
  'folhoso',
  '牛百叶',
  '牛瓣胃',
  '叶胃',
];

export const DEFAULT_BROAD_TERMS = [
  'beef tripe',
  'bovine stomach',
  'beef stomach',
  'edible beef offal',
  'mondongo',
  'panza',
  'estomago bovino',
  'estómago bovino',
  'visceras bovinas',
  'vísceras bovinas',
  'subproductos bovinos',
  'bucho bovino',
  'miudos bovinos',
  'miúdos bovinos',
  'subprodutos bovinos',
  '牛肚',
  '毛肚',
];

export const DEFAULT_EXCLUDED_TERMS = [
  'rumen',
  'honeycomb tripe',
  'mixed beef tripe',
  'beef intestine',
  'casings',
];
